version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/tidyverse:3.4.3
    steps:
      - checkout
      - run: 
          name: Greeting
          command: echo Starting build of BikeCount
      - run:
          command: R --version
      - run:
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
         command: R -e 'devtools::check()'
      - run:
          name: Print the Current Time
          command: date